shortener.cache:
  size: 20 #Max cache to 20 just for the example. It can get a lot larger than this.


spring:
  application.name: urlshortener
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


